---
date: "2025-07-08T17:55:28+08:00"
description: Well,I have time for all  as long as my phone's battery is full! 
showTableOfContents: true
tags:
- Mobile Games
- Game Design
title: "From Connecting Dots to Saving the King: Old & New Puzzle Favourites" 
draft: true
type: post
weight: 25
---

I have been playing puzzle games long before I joined the industry. During my career I kept playing all sorts of puzzle games to be able to compare what is out there besides the games I have been part of. 

## Connecting Dots, Challenging Friends

I used to have an iPod, the one look like an iPhone and it had everything (except it wasn't a phone 😅). Two Dots was one of the games we (me and my collegue) used to play on that device and we challenge each other on every level. During that time we were admiring how simple was the design. 


I have started playing the game couple months back to remind myself what was really attracted me to the game. Of course it has changed a lot with various additions to the main game but there were still pieces of what I enjoyed:

- Main game board still *as clean as possible*
- There is more live-ops going on with the events (although missing daily quests) 
- Learning curve of the game doesn't feel much off

Currently I feel like the game has been transformed to a bit more "caotic" state with the changes in years: 

- crazy amount of pop-ups I need to clear for 30 seconds before I start the game
- amount of ad places and ads shown 
- new game modes doesn't really feels as satisfying 


## Everything is Glamorous and Faster than Ever

Maybe you haven't played Two Dots but if you're in the industry you definitely played Royal Match. It is has been installed over 300M since it's launch in 2021. Everyone talks about the game one way or the other but I wanted to mention as comparison to games that has been around for more than 10 years. 

Royal Match can take ones eyes with all bright colours, snappy animations and smooth 





