baseURL: hazelsinki.me
defaultContentLanguage: en
enableEmoji: yes
enableRobotsTXT: yes
languageCode: en
pygmentsStyle: monokai
theme: gokarna-hugo
title: Hazelsinki
params:
  avatarAltText: avatar
  avatarSize: size-m
  avatarURL: /images/hazel_200px_03.jpg
  customHeadHTML: "    <!-- KaTeX -->\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css\"
    integrity=\"sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC\"
    crossorigin=\"anonymous\">\n    <script defer src=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js\"
    integrity=\"sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja\"
    crossorigin=\"anonymous\"></script>\n    <script defer src=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js\"
    integrity=\"sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR\"
    crossorigin=\"anonymous\"></script>\n    <script>\n      document.addEventListener(\"DOMContentLoaded\",
    function() {\n        renderMathInElement(document.body, {\n          // customised
    options\n          // • auto-render specific keys, e.g.:\n          delimiters:
    [\n            {left: '$$', right: '$$', display: true},\n            {left: '$',
    right: '$', display: false},\n          ],\n          // • rendering keys, e.g.:\n
    \         throwOnError : false\n        });\n      });\n    </script>\n  "
  description: Data Analyst by day, Lindy Hop dancer by night
  footer:
  metaKeywords:
  showBackToTopButton: yes
  socialIcons:
    - name: linkedin
      url: https://www.linkedin.com/in/hazzelkavili/
    - name: instagram
      url: https://www.instagram.com/hazelsinki/
    - name: email
      url: mailto:hazzelkavili@gmail.com
menu:
  main:
    - name: Home
      pre: <span data-feather='home'></span>
      url: /
      weight: 1
    - name: About
      pre: <span data-feather='user'></span>
      url: /about/
      weight: 2 
    - name: Posts
      pre: <span data-feather='book'></span>
      url: /posts/
      weight: 3
    - name: Projects
      pre: <span data-feather='code'></span>
      url: /projects/
      weight: 4
    - name: Tags
      pre: <span data-feather='tag'></span>
      url: /tags/
      weight: 5

markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 1
  goldmark:
    renderer:
      unsafe: true  
minify:
  minifyOutput: yes
